import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-opensans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${openSans.variable}`}>
      <body className="h-screen w-screen bg-background-swirl bg-[-640px_-320px] bg-no-repeat before:bg-gradient-filter before:mix-blend-multiply antialiased">
        <main className="h-full w-full px-32 py-36 bg-gradient-filter">
          <div className="h-full w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
